### ISSUE TITLE
Consider showing full dir structure for Argo CD

### ISSUE THREAD

**Issue by todaywasawesome** [kostis-codefresh/gitops-environment-promotion#1]
This repo does a great job of showing how to manage configs across environments but part of the goal is to show people how to manage these resources using GitOps. I think it would be good to show something like this dir structure [https://github.com/todaywasawesome/oss-apps](https://github.com/todaywasawesome/oss-apps) so we can show how GitOps app config should be separated from the manifests.

**Comment by kostis-codefresh** [comment]
This has now been covered in https://github.com/kostis-codefresh/many-appsets-demo

Full blog post at https://codefresh.io/blog/how-to-structure-your-argo-cd-repositories-using-application-sets/
