### ISSUE TITLE
question: how to use the structure with argocd

### ISSUE THREAD

**Issue by deepseeksss** [kostis-codefresh/gitops-environment-promotion#4]
hello, i'm new to argocd & gitops,  i have reading your great blog and i am the codefresh's user

afther reading the blog, i have a question:

if i have dev, test, stag, prod...multiple envs

i just use one repo structure as this repo and multiple applications in argocd ?

**Comment by kostis-codefresh** [comment]
Hello

Depends on what you mean by "envs". Is it different clusters? Or same cluster? Also do you have one Argo CD instance or many.

In general however, yes you have one Git repo and multiple apps in Argo CD

Check https://codefresh.io/blog/a-comprehensive-overview-of-argo-cd-architectures-2023/ and also https://argo-cd.readthedocs.io/en/stable/user-guide/application-set/

For more info please join the CNCF slack channels for Argo CD at https://argoproj.github.io/community/join-slack
