### ISSUE TITLE
missing files referenced in the README

### ISSUE THREAD

**Issue by adamwolfe-tc** [kostis-codefresh/gitops-environment-promotion#5]
in this README code block:

```
resources:
- ../../base

components:
  - ../../variants/non-prod
  - ../../variants/asia

patchesStrategicMerge:
- deployment.yml
- version.yml
- replicas.yml
- settings.yml
```

the files `settings.yml` and `version.yml` are referenced and explained in the comments following.  but there is no `settings.yml` nor `version.yml` within any of the directories mentioned:

```
resources:
- ../../base

components:
  - ../../variants/non-prod
  - ../../variants/asia
```

**Comment by kostis-codefresh** [comment]
Hello

The files are in the same folder as the kustomization file itself.
For the example mentioned in the README they are at https://github.com/kostis-codefresh/gitops-environment-promotion/blob/main/envs/staging-asia/version.yml and https://github.com/kostis-codefresh/gitops-environment-promotion/blob/main/envs/staging-asia/settings.yml

Does that answer your question?

**Comment by adamwolfe-tc** [comment]
yep.  I think that covers it.  was just confusing (to me) since that path wasn't called out.
